// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/FM1337/ASB/internal/database/schema"
	"github.com/FM1337/ASB/internal/ent/server"
	"github.com/FM1337/ASB/internal/ent/serverconfig"
	"github.com/FM1337/ASB/internal/ent/wordblacklist"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	serverMixin := schema.Server{}.Mixin()
	serverMixinFields0 := serverMixin[0].Fields()
	_ = serverMixinFields0
	serverFields := schema.Server{}.Fields()
	_ = serverFields
	// serverDescCreateTime is the schema descriptor for create_time field.
	serverDescCreateTime := serverMixinFields0[0].Descriptor()
	// server.DefaultCreateTime holds the default value on creation for the create_time field.
	server.DefaultCreateTime = serverDescCreateTime.Default.(func() time.Time)
	// serverDescUpdateTime is the schema descriptor for update_time field.
	serverDescUpdateTime := serverMixinFields0[1].Descriptor()
	// server.DefaultUpdateTime holds the default value on creation for the update_time field.
	server.DefaultUpdateTime = serverDescUpdateTime.Default.(func() time.Time)
	// server.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	server.UpdateDefaultUpdateTime = serverDescUpdateTime.UpdateDefault.(func() time.Time)
	// serverDescEnabled is the schema descriptor for enabled field.
	serverDescEnabled := serverFields[2].Descriptor()
	// server.DefaultEnabled holds the default value on creation for the enabled field.
	server.DefaultEnabled = serverDescEnabled.Default.(bool)
	serverconfigMixin := schema.ServerConfig{}.Mixin()
	serverconfigMixinFields0 := serverconfigMixin[0].Fields()
	_ = serverconfigMixinFields0
	serverconfigFields := schema.ServerConfig{}.Fields()
	_ = serverconfigFields
	// serverconfigDescCreateTime is the schema descriptor for create_time field.
	serverconfigDescCreateTime := serverconfigMixinFields0[0].Descriptor()
	// serverconfig.DefaultCreateTime holds the default value on creation for the create_time field.
	serverconfig.DefaultCreateTime = serverconfigDescCreateTime.Default.(func() time.Time)
	// serverconfigDescUpdateTime is the schema descriptor for update_time field.
	serverconfigDescUpdateTime := serverconfigMixinFields0[1].Descriptor()
	// serverconfig.DefaultUpdateTime holds the default value on creation for the update_time field.
	serverconfig.DefaultUpdateTime = serverconfigDescUpdateTime.Default.(func() time.Time)
	// serverconfig.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	serverconfig.UpdateDefaultUpdateTime = serverconfigDescUpdateTime.UpdateDefault.(func() time.Time)
	// serverconfigDescRemoveRoles is the schema descriptor for remove_roles field.
	serverconfigDescRemoveRoles := serverconfigFields[0].Descriptor()
	// serverconfig.DefaultRemoveRoles holds the default value on creation for the remove_roles field.
	serverconfig.DefaultRemoveRoles = serverconfigDescRemoveRoles.Default.(bool)
	// serverconfigDescGiveRole is the schema descriptor for give_role field.
	serverconfigDescGiveRole := serverconfigFields[1].Descriptor()
	// serverconfig.DefaultGiveRole holds the default value on creation for the give_role field.
	serverconfig.DefaultGiveRole = serverconfigDescGiveRole.Default.(bool)
	// serverconfigDescTimeout is the schema descriptor for timeout field.
	serverconfigDescTimeout := serverconfigFields[2].Descriptor()
	// serverconfig.DefaultTimeout holds the default value on creation for the timeout field.
	serverconfig.DefaultTimeout = serverconfigDescTimeout.Default.(bool)
	// serverconfigDescKick is the schema descriptor for kick field.
	serverconfigDescKick := serverconfigFields[3].Descriptor()
	// serverconfig.DefaultKick holds the default value on creation for the kick field.
	serverconfig.DefaultKick = serverconfigDescKick.Default.(bool)
	// serverconfigDescBan is the schema descriptor for ban field.
	serverconfigDescBan := serverconfigFields[4].Descriptor()
	// serverconfig.DefaultBan holds the default value on creation for the ban field.
	serverconfig.DefaultBan = serverconfigDescBan.Default.(bool)
	// serverconfigDescCheckInvites is the schema descriptor for check_invites field.
	serverconfigDescCheckInvites := serverconfigFields[5].Descriptor()
	// serverconfig.DefaultCheckInvites holds the default value on creation for the check_invites field.
	serverconfig.DefaultCheckInvites = serverconfigDescCheckInvites.Default.(bool)
	// serverconfigDescCheckLinks is the schema descriptor for check_links field.
	serverconfigDescCheckLinks := serverconfigFields[6].Descriptor()
	// serverconfig.DefaultCheckLinks holds the default value on creation for the check_links field.
	serverconfig.DefaultCheckLinks = serverconfigDescCheckLinks.Default.(bool)
	// serverconfigDescRatelimit is the schema descriptor for ratelimit field.
	serverconfigDescRatelimit := serverconfigFields[7].Descriptor()
	// serverconfig.DefaultRatelimit holds the default value on creation for the ratelimit field.
	serverconfig.DefaultRatelimit = serverconfigDescRatelimit.Default.(bool)
	// serverconfigDescAlerts is the schema descriptor for alerts field.
	serverconfigDescAlerts := serverconfigFields[8].Descriptor()
	// serverconfig.DefaultAlerts holds the default value on creation for the alerts field.
	serverconfig.DefaultAlerts = serverconfigDescAlerts.Default.(bool)
	// serverconfigDescFlagLinks is the schema descriptor for flag_links field.
	serverconfigDescFlagLinks := serverconfigFields[9].Descriptor()
	// serverconfig.DefaultFlagLinks holds the default value on creation for the flag_links field.
	serverconfig.DefaultFlagLinks = serverconfigDescFlagLinks.Default.(bool)
	// serverconfigDescRatelimitMessage is the schema descriptor for ratelimit_message field.
	serverconfigDescRatelimitMessage := serverconfigFields[15].Descriptor()
	// serverconfig.DefaultRatelimitMessage holds the default value on creation for the ratelimit_message field.
	serverconfig.DefaultRatelimitMessage = serverconfigDescRatelimitMessage.Default.(int)
	wordblacklistMixin := schema.WordBlacklist{}.Mixin()
	wordblacklistMixinFields0 := wordblacklistMixin[0].Fields()
	_ = wordblacklistMixinFields0
	wordblacklistFields := schema.WordBlacklist{}.Fields()
	_ = wordblacklistFields
	// wordblacklistDescCreateTime is the schema descriptor for create_time field.
	wordblacklistDescCreateTime := wordblacklistMixinFields0[0].Descriptor()
	// wordblacklist.DefaultCreateTime holds the default value on creation for the create_time field.
	wordblacklist.DefaultCreateTime = wordblacklistDescCreateTime.Default.(func() time.Time)
	// wordblacklistDescUpdateTime is the schema descriptor for update_time field.
	wordblacklistDescUpdateTime := wordblacklistMixinFields0[1].Descriptor()
	// wordblacklist.DefaultUpdateTime holds the default value on creation for the update_time field.
	wordblacklist.DefaultUpdateTime = wordblacklistDescUpdateTime.Default.(func() time.Time)
	// wordblacklist.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	wordblacklist.UpdateDefaultUpdateTime = wordblacklistDescUpdateTime.UpdateDefault.(func() time.Time)
}
