// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/FM1337/ASB/internal/ent/predicate"
	"github.com/FM1337/ASB/internal/ent/server"
	"github.com/FM1337/ASB/internal/ent/wordblacklist"
)

// WordBlacklistQuery is the builder for querying WordBlacklist entities.
type WordBlacklistQuery struct {
	config
	ctx        *QueryContext
	order      []wordblacklist.OrderOption
	inters     []Interceptor
	predicates []predicate.WordBlacklist
	withServer *ServerQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WordBlacklistQuery builder.
func (wbq *WordBlacklistQuery) Where(ps ...predicate.WordBlacklist) *WordBlacklistQuery {
	wbq.predicates = append(wbq.predicates, ps...)
	return wbq
}

// Limit the number of records to be returned by this query.
func (wbq *WordBlacklistQuery) Limit(limit int) *WordBlacklistQuery {
	wbq.ctx.Limit = &limit
	return wbq
}

// Offset to start from.
func (wbq *WordBlacklistQuery) Offset(offset int) *WordBlacklistQuery {
	wbq.ctx.Offset = &offset
	return wbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wbq *WordBlacklistQuery) Unique(unique bool) *WordBlacklistQuery {
	wbq.ctx.Unique = &unique
	return wbq
}

// Order specifies how the records should be ordered.
func (wbq *WordBlacklistQuery) Order(o ...wordblacklist.OrderOption) *WordBlacklistQuery {
	wbq.order = append(wbq.order, o...)
	return wbq
}

// QueryServer chains the current query on the "server" edge.
func (wbq *WordBlacklistQuery) QueryServer() *ServerQuery {
	query := (&ServerClient{config: wbq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordblacklist.Table, wordblacklist.FieldID, selector),
			sqlgraph.To(server.Table, server.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, wordblacklist.ServerTable, wordblacklist.ServerPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(wbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WordBlacklist entity from the query.
// Returns a *NotFoundError when no WordBlacklist was found.
func (wbq *WordBlacklistQuery) First(ctx context.Context) (*WordBlacklist, error) {
	nodes, err := wbq.Limit(1).All(setContextOp(ctx, wbq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wordblacklist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wbq *WordBlacklistQuery) FirstX(ctx context.Context) *WordBlacklist {
	node, err := wbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WordBlacklist ID from the query.
// Returns a *NotFoundError when no WordBlacklist ID was found.
func (wbq *WordBlacklistQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wbq.Limit(1).IDs(setContextOp(ctx, wbq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wordblacklist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wbq *WordBlacklistQuery) FirstIDX(ctx context.Context) int {
	id, err := wbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WordBlacklist entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WordBlacklist entity is found.
// Returns a *NotFoundError when no WordBlacklist entities are found.
func (wbq *WordBlacklistQuery) Only(ctx context.Context) (*WordBlacklist, error) {
	nodes, err := wbq.Limit(2).All(setContextOp(ctx, wbq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wordblacklist.Label}
	default:
		return nil, &NotSingularError{wordblacklist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wbq *WordBlacklistQuery) OnlyX(ctx context.Context) *WordBlacklist {
	node, err := wbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WordBlacklist ID in the query.
// Returns a *NotSingularError when more than one WordBlacklist ID is found.
// Returns a *NotFoundError when no entities are found.
func (wbq *WordBlacklistQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wbq.Limit(2).IDs(setContextOp(ctx, wbq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wordblacklist.Label}
	default:
		err = &NotSingularError{wordblacklist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wbq *WordBlacklistQuery) OnlyIDX(ctx context.Context) int {
	id, err := wbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WordBlacklists.
func (wbq *WordBlacklistQuery) All(ctx context.Context) ([]*WordBlacklist, error) {
	ctx = setContextOp(ctx, wbq.ctx, "All")
	if err := wbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WordBlacklist, *WordBlacklistQuery]()
	return withInterceptors[[]*WordBlacklist](ctx, wbq, qr, wbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wbq *WordBlacklistQuery) AllX(ctx context.Context) []*WordBlacklist {
	nodes, err := wbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WordBlacklist IDs.
func (wbq *WordBlacklistQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wbq.ctx.Unique == nil && wbq.path != nil {
		wbq.Unique(true)
	}
	ctx = setContextOp(ctx, wbq.ctx, "IDs")
	if err = wbq.Select(wordblacklist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wbq *WordBlacklistQuery) IDsX(ctx context.Context) []int {
	ids, err := wbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wbq *WordBlacklistQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wbq.ctx, "Count")
	if err := wbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wbq, querierCount[*WordBlacklistQuery](), wbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wbq *WordBlacklistQuery) CountX(ctx context.Context) int {
	count, err := wbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wbq *WordBlacklistQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wbq.ctx, "Exist")
	switch _, err := wbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wbq *WordBlacklistQuery) ExistX(ctx context.Context) bool {
	exist, err := wbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WordBlacklistQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wbq *WordBlacklistQuery) Clone() *WordBlacklistQuery {
	if wbq == nil {
		return nil
	}
	return &WordBlacklistQuery{
		config:     wbq.config,
		ctx:        wbq.ctx.Clone(),
		order:      append([]wordblacklist.OrderOption{}, wbq.order...),
		inters:     append([]Interceptor{}, wbq.inters...),
		predicates: append([]predicate.WordBlacklist{}, wbq.predicates...),
		withServer: wbq.withServer.Clone(),
		// clone intermediate query.
		sql:  wbq.sql.Clone(),
		path: wbq.path,
	}
}

// WithServer tells the query-builder to eager-load the nodes that are connected to
// the "server" edge. The optional arguments are used to configure the query builder of the edge.
func (wbq *WordBlacklistQuery) WithServer(opts ...func(*ServerQuery)) *WordBlacklistQuery {
	query := (&ServerClient{config: wbq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wbq.withServer = query
	return wbq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WordBlacklist.Query().
//		GroupBy(wordblacklist.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wbq *WordBlacklistQuery) GroupBy(field string, fields ...string) *WordBlacklistGroupBy {
	wbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WordBlacklistGroupBy{build: wbq}
	grbuild.flds = &wbq.ctx.Fields
	grbuild.label = wordblacklist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.WordBlacklist.Query().
//		Select(wordblacklist.FieldCreateTime).
//		Scan(ctx, &v)
func (wbq *WordBlacklistQuery) Select(fields ...string) *WordBlacklistSelect {
	wbq.ctx.Fields = append(wbq.ctx.Fields, fields...)
	sbuild := &WordBlacklistSelect{WordBlacklistQuery: wbq}
	sbuild.label = wordblacklist.Label
	sbuild.flds, sbuild.scan = &wbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WordBlacklistSelect configured with the given aggregations.
func (wbq *WordBlacklistQuery) Aggregate(fns ...AggregateFunc) *WordBlacklistSelect {
	return wbq.Select().Aggregate(fns...)
}

func (wbq *WordBlacklistQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wbq); err != nil {
				return err
			}
		}
	}
	for _, f := range wbq.ctx.Fields {
		if !wordblacklist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wbq.path != nil {
		prev, err := wbq.path(ctx)
		if err != nil {
			return err
		}
		wbq.sql = prev
	}
	return nil
}

func (wbq *WordBlacklistQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WordBlacklist, error) {
	var (
		nodes       = []*WordBlacklist{}
		_spec       = wbq.querySpec()
		loadedTypes = [1]bool{
			wbq.withServer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WordBlacklist).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WordBlacklist{config: wbq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(wbq.modifiers) > 0 {
		_spec.Modifiers = wbq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wbq.withServer; query != nil {
		if err := wbq.loadServer(ctx, query, nodes,
			func(n *WordBlacklist) { n.Edges.Server = []*Server{} },
			func(n *WordBlacklist, e *Server) { n.Edges.Server = append(n.Edges.Server, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wbq *WordBlacklistQuery) loadServer(ctx context.Context, query *ServerQuery, nodes []*WordBlacklist, init func(*WordBlacklist), assign func(*WordBlacklist, *Server)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*WordBlacklist)
	nids := make(map[int]map[*WordBlacklist]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(wordblacklist.ServerTable)
		s.Join(joinT).On(s.C(server.FieldID), joinT.C(wordblacklist.ServerPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(wordblacklist.ServerPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(wordblacklist.ServerPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*WordBlacklist]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Server](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "server" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (wbq *WordBlacklistQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wbq.querySpec()
	if len(wbq.modifiers) > 0 {
		_spec.Modifiers = wbq.modifiers
	}
	_spec.Node.Columns = wbq.ctx.Fields
	if len(wbq.ctx.Fields) > 0 {
		_spec.Unique = wbq.ctx.Unique != nil && *wbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wbq.driver, _spec)
}

func (wbq *WordBlacklistQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wordblacklist.Table, wordblacklist.Columns, sqlgraph.NewFieldSpec(wordblacklist.FieldID, field.TypeInt))
	_spec.From = wbq.sql
	if unique := wbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wbq.path != nil {
		_spec.Unique = true
	}
	if fields := wbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wordblacklist.FieldID)
		for i := range fields {
			if fields[i] != wordblacklist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wbq *WordBlacklistQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wbq.driver.Dialect())
	t1 := builder.Table(wordblacklist.Table)
	columns := wbq.ctx.Fields
	if len(columns) == 0 {
		columns = wordblacklist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wbq.sql != nil {
		selector = wbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wbq.ctx.Unique != nil && *wbq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range wbq.modifiers {
		m(selector)
	}
	for _, p := range wbq.predicates {
		p(selector)
	}
	for _, p := range wbq.order {
		p(selector)
	}
	if offset := wbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (wbq *WordBlacklistQuery) Modify(modifiers ...func(s *sql.Selector)) *WordBlacklistSelect {
	wbq.modifiers = append(wbq.modifiers, modifiers...)
	return wbq.Select()
}

// WordBlacklistGroupBy is the group-by builder for WordBlacklist entities.
type WordBlacklistGroupBy struct {
	selector
	build *WordBlacklistQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wbgb *WordBlacklistGroupBy) Aggregate(fns ...AggregateFunc) *WordBlacklistGroupBy {
	wbgb.fns = append(wbgb.fns, fns...)
	return wbgb
}

// Scan applies the selector query and scans the result into the given value.
func (wbgb *WordBlacklistGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wbgb.build.ctx, "GroupBy")
	if err := wbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WordBlacklistQuery, *WordBlacklistGroupBy](ctx, wbgb.build, wbgb, wbgb.build.inters, v)
}

func (wbgb *WordBlacklistGroupBy) sqlScan(ctx context.Context, root *WordBlacklistQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wbgb.fns))
	for _, fn := range wbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wbgb.flds)+len(wbgb.fns))
		for _, f := range *wbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WordBlacklistSelect is the builder for selecting fields of WordBlacklist entities.
type WordBlacklistSelect struct {
	*WordBlacklistQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wbs *WordBlacklistSelect) Aggregate(fns ...AggregateFunc) *WordBlacklistSelect {
	wbs.fns = append(wbs.fns, fns...)
	return wbs
}

// Scan applies the selector query and scans the result into the given value.
func (wbs *WordBlacklistSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wbs.ctx, "Select")
	if err := wbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WordBlacklistQuery, *WordBlacklistSelect](ctx, wbs.WordBlacklistQuery, wbs, wbs.inters, v)
}

func (wbs *WordBlacklistSelect) sqlScan(ctx context.Context, root *WordBlacklistQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wbs.fns))
	for _, fn := range wbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (wbs *WordBlacklistSelect) Modify(modifiers ...func(s *sql.Selector)) *WordBlacklistSelect {
	wbs.modifiers = append(wbs.modifiers, modifiers...)
	return wbs
}
