// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)

// ServerConfig is the predicate function for serverconfig builders.
type ServerConfig func(*sql.Selector)

// WordBlacklist is the predicate function for wordblacklist builders.
type WordBlacklist func(*sql.Selector)
