// Code generated by ent, DO NOT EDIT.

package spammer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/FM1337/ASB/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Spammer {
	return predicate.Spammer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Spammer {
	return predicate.Spammer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Spammer {
	return predicate.Spammer(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldUpdateTime, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldUserID, v))
}

// LastFlagged applies equality check predicate on the "last_flagged" field. It's identical to LastFlaggedEQ.
func LastFlagged(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldLastFlagged, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldLTE(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Spammer {
	return predicate.Spammer(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Spammer {
	return predicate.Spammer(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Spammer {
	return predicate.Spammer(sql.FieldContainsFold(FieldUserID, v))
}

// RemovedRolesIsNil applies the IsNil predicate on the "removed_roles" field.
func RemovedRolesIsNil() predicate.Spammer {
	return predicate.Spammer(sql.FieldIsNull(FieldRemovedRoles))
}

// RemovedRolesNotNil applies the NotNil predicate on the "removed_roles" field.
func RemovedRolesNotNil() predicate.Spammer {
	return predicate.Spammer(sql.FieldNotNull(FieldRemovedRoles))
}

// LastFlaggedEQ applies the EQ predicate on the "last_flagged" field.
func LastFlaggedEQ(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldEQ(FieldLastFlagged, v))
}

// LastFlaggedNEQ applies the NEQ predicate on the "last_flagged" field.
func LastFlaggedNEQ(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldNEQ(FieldLastFlagged, v))
}

// LastFlaggedIn applies the In predicate on the "last_flagged" field.
func LastFlaggedIn(vs ...time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldIn(FieldLastFlagged, vs...))
}

// LastFlaggedNotIn applies the NotIn predicate on the "last_flagged" field.
func LastFlaggedNotIn(vs ...time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldNotIn(FieldLastFlagged, vs...))
}

// LastFlaggedGT applies the GT predicate on the "last_flagged" field.
func LastFlaggedGT(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldGT(FieldLastFlagged, v))
}

// LastFlaggedGTE applies the GTE predicate on the "last_flagged" field.
func LastFlaggedGTE(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldGTE(FieldLastFlagged, v))
}

// LastFlaggedLT applies the LT predicate on the "last_flagged" field.
func LastFlaggedLT(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldLT(FieldLastFlagged, v))
}

// LastFlaggedLTE applies the LTE predicate on the "last_flagged" field.
func LastFlaggedLTE(v time.Time) predicate.Spammer {
	return predicate.Spammer(sql.FieldLTE(FieldLastFlagged, v))
}

// HasServer applies the HasEdge predicate on the "server" edge.
func HasServer() predicate.Spammer {
	return predicate.Spammer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ServerTable, ServerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServerWith applies the HasEdge predicate on the "server" edge with a given conditions (other predicates).
func HasServerWith(preds ...predicate.Server) predicate.Spammer {
	return predicate.Spammer(func(s *sql.Selector) {
		step := newServerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Spammer) predicate.Spammer {
	return predicate.Spammer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Spammer) predicate.Spammer {
	return predicate.Spammer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Spammer) predicate.Spammer {
	return predicate.Spammer(sql.NotPredicates(p))
}
